# SPDX-FileCopyrightText: 2025 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

name: Go test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'
          
      - name: Run tests
        run: |
            go get .
            go test
